# Generated by Django 2.1.7 on 2019-05-29 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccompanyingSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Комментарий')),
                ('date_of_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contact_person', models.CharField(max_length=200, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(max_length=50, verbose_name='Контактный телефон')),
                ('contact_mail', models.CharField(max_length=50, verbose_name='E-mail адрес')),
                ('customer_name', models.CharField(blank=True, default='ТОВ "НКТ"', max_length=200, null=True, verbose_name='Название контрагента')),
                ('customer_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Код контрагента')),
                ('warranty', models.IntegerField(blank=True, default=1, null=True, verbose_name='Количество коробок')),
                ('itemProvider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ItemProvider', verbose_name='Поставщик / Сервисный центр')),
            ],
            options={
                'verbose_name': 'Сопроводительные листы',
                'db_table': 'base_accompanyingsheet',
                'ordering': ['-date_of_create', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AccompanyingSheetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Артикул')),
                ('item_name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='Производитель')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('malfunction', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Проблема')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий')),
                ('equipment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комплектация')),
                ('item_purchase_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата покупки')),
                ('count', models.IntegerField(default=1, verbose_name='Количество')),
                ('accompanying_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accompanying_sheets.AccompanyingSheet')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.ServiceOrder')),
            ],
            options={
                'db_table': 'base_accompanyingsheetitem',
            },
        ),
    ]
