# Generated by Django 2.1.7 on 2019-09-03 11:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_itemprovider_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_num', models.IntegerField(blank=True, null=True, verbose_name='Номер документа')),
                ('date_document', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('date_of_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('buyer_person', models.CharField(blank=True, default='Розничный', max_length=200, null=True, verbose_name='Покупатель')),
                ('buyer_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Контактный телефон')),
                ('comment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Гарантийные талоны',
                'ordering': ['-date_of_create', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyCardItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('count', models.IntegerField(default=1, verbose_name='Количество')),
                ('serial_number', models.CharField(blank=True, max_length=200, verbose_name='Серийный номер')),
                ('warranty', models.IntegerField(blank=True, null=True, verbose_name='Гарантийный срок')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.ServiceOrder')),
                ('itemProvider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ItemProvider', verbose_name='Поставщик / Сервисный центр')),
                ('warrantycard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warrantycards.WarrantyCard')),
            ],
            options={
                'verbose_name': 'Пункты гарантийного талона',
            },
        ),
    ]
