# Generated by Django 2.1.7 on 2019-09-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrantycards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantycarditem',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Цена'),
        ),
    ]
