# Generated by Django 2.1.7 on 2019-08-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='local_phone',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
