# Generated by Django 2.1.7 on 2019-05-29 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='Производитель')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('price', models.FloatField(blank=True, default=None, null=True, verbose_name='Стоимость')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Артикул у поставщика')),
                ('item_purchase_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата покупки')),
                ('purchase_document', models.CharField(blank=True, default='', max_length=200, verbose_name='Документ о покупке/гарантии')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий')),
                ('warranty', models.IntegerField(blank=True, null=True, verbose_name='Гарантия')),
                ('section', models.CharField(blank=True, max_length=100, null=True, verbose_name='Раздел')),
                ('itemProvider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ItemProvider')),
            ],
            options={
                'verbose_name': 'Серийный номер',
                'verbose_name_plural': 'Серийные номера',
                'db_table': 'base_serialnumbers',
                'ordering': ['-item_purchase_date', 'serial_number'],
            },
        ),
    ]
