# Generated by Django 2.1.7 on 2019-06-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprovider',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL тех портала'),
        ),
    ]
